---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khanhkhanh1234/argocd-training.git
    targetRevision: HEAD
    path: environments/staging/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true